### ISSUE TITLE
Add internationalization support to struct/form labels

### ISSUE THREAD

**Issue by gnewton** [joncalhoun/form#2]
Form labels only support single languages (from what I see...). Perhaps label could be extended to support multiple languages.
It could look something like this:

Now:

```
type address struct {
	Street1 string
	Street2 string
	City    string
	State   string
	Zip     string ``form:"label=Postal Code"`
}
```

Perhaps this could be changed to something like:
```
type address struct {
	Street1 string
	Street2 string
	City    string
	State   string
	Zip     string `form:"label.en=Postal Code,label.fr=Code Postal,label.jp=郵便番号" `
}
```

**Comment by joncalhoun** [comment]
I like the idea, but I'll probably have to think about *how* to make it work a bit more. My biggest fear with struct tags is that the can get huge quick and could be super annoying to manage. I already feel there are a bit too many options but haven't explored alternatives.

One option I may look into is providing a config file - something like a YAML file - where each field is described. Eg:

```yaml
Zip:
  label: 
    en-us: Zip Code
    en-uk: Postal Code
    fr: Code Postal
    jp: 郵便番号
```

I have no idea what the format would be, but this way you could just customize the parts you care about then maybe provide that to the builder when you set it up. Something like:

```go
fb := form.Builder{
  InputTemplate: ...,
  I18n: reader_for_yaml,
}
```

**Comment by gnewton** [comment]
Understood.
See https://github.com/nicksnyder/go-i18n which has i18n bundles similar to what you are suggesting (plus more)...

:-)

**Comment by joncalhoun** [comment]
After looking at examples and thinking about this a bit I think @raspi has the right approach. Translation can be added to templates using almost any existing i18n library, so it doesn't make sense to reinvent the wheel and add it here.

I am going to close the issue, but I appreciate the suggestion @gnewton!
