### ISSUE TITLE
CSS/JS library/framework agnostic?

### ISSUE THREAD

**Issue by prologic** [joncalhoun/form#4]
Is this forms library agnostic of any particular CSS?JS libraries/frameworks? For example can I use [PicnicCSS](https://picnicss.com) or [SpectreCSS](https://picturepan2.github.io/spectre/) or some [classless CSS library](https://www.google.com/search?q=classless%20css&btnK)? Sorry I haven't looked too deeply at your codebase to answer this myself :/

**Comment by joncalhoun** [comment]
It is library agnostic. You provide an HTML template that it uses to generate forms, so your template can use whatever class names you want.

The examples dir actually has an example with both bootstrap and tailwindcss - https://github.com/joncalhoun/form/tree/master/examples
